# HTTP Server
server:
  port: 16346  # HTTP (Tomcat) port

spring:
  application:
    name: ts-travel2-service
  data:
    mongodb:
      host: ts-travel2-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017
management:
  endpoints:
    web:
      exposure:
        include: prometheus
swagger:
  controllerPackage: travel2.controller