spring:
  application:
    name: ts-route-service
  data:
    mongodb:
      host: ts-route-mongo
      database: ts-route-mongo
      port: 27017
management:
  endpoints:
    web:
      exposure:
        include: prometheus
# HTTP Server
server:
  port: 11178  # HTTP (Tomcat) port

swagger:
  controllerPackage: route.controller